openapi: 3.0.0
info:
  title: Sunglasses Store API
  version: 1.0.0
  description: API for managing a sunglasses store

servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /users/login:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                  description: The user's email
                password:
                  type: string
                  example: password
                  description: The user's password (at least 5 characters)
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: jwt-token
        "401":
          description: Invalid credentials
        "400":
          description: Validation errors

  /brands:
    get:
      summary: Get all brands
      description: Returns a list of all available brands
      responses:
        "200":
          description: A list of brands
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Oakley

  /brands/{brand}:
    get:
      summary: Get products by brand
      description: Returns a list of products for a specific brand
      parameters:
        - in: path
          name: brand
          required: true
          schema:
            type: string
          description: The name of the brand
      responses:
        "200":
          description: A list of products for the specified brand
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Oakley Sunglasses
                    categoryId:
                      type: integer
                      example: 1
        "404":
          description: Brand not found

  /products/search:
    get:
      summary: Search for products
      description: Searches for products by name
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: The search query
      responses:
        "200":
          description: A list of products matching the search query
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Oakley Sunglasses
                    categoryId:
                      type: integer
                      example: 1

  /cart:
    get:
      summary: Get user's cart
      description: Returns the current cart for the authenticated user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of items in the user's cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: integer
                          example: 1
                        quantity:
                          type: integer
                          example: 2
        "401":
          description: Unauthorized

    post:
      summary: Add product to cart
      description: Adds a product to the authenticated user's cart
      security:
        -
