openapi: 3.0.0
info:
  title: Sunglasses Store API
  version: 1.0.0
paths:
  /me/cart:
    get:
      summary: Get user cart
      responses:
        "200":
          description: Successful response
    post:
      summary: Add product to cart
      responses:
        "200":
          description: Successful response
  /me/cart/{productId}:
    delete:
      summary: Delete a product from the cart
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
    post:
      summary: Change quantity of a product in the cart
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
  /brands/{id}/products:
    get:
      summary: Get list of products for a specific brand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
  /products:
    get:
      summary: Get list of all products
      responses:
        "200":
          description: Successful response
